### PR TITLE
users can update profile

### PR DESCRIPTION
**Pull request by Michael-Saechao**

### CODE REVIEW

**Comment by jakewest35** [comment]
@Michael-Saechao Please resolve the file conflicts and pull the linter from main so the action can be ran.

**Review by Michael-Saechao — COMMENTED** [review]
accept changes

**Review by Michael-Saechao — COMMENTED** [review]
accept changes

**Review by Michael-Saechao — COMMENTED** [review]
completed review

**Review by jakewest35 — APPROVED** [review]

**Pull request merged**
